module.exports = {
  CONSECUTIVE_MESSAGES_TIMEOUT_MS: 3000,
  MAX_CONSECUTIVE_MESSAGES: 5,
  MAX_MESSAGES: 1000,
  MAX_MESSAGE_LENGTH: 100,
  MIN_MESSAGE_LENGTH: 1,
  MAX_NAME_LENGTH: 25,
  MIN_NAME_LENGTH: 1,
};
